{{- if .Values.site24x7Agent.createConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "site24x7.fullname" . }}
  labels:
    {{- include "site24x7.labels" . | nindent 4 }}
data:
  NODE_AGENT_VERSION: "2000"
  CLUSTER_AGENT_VERSION: "100"
  SETTINGS: |
    {
      "kubernetes": "300",
      "daemonsets": "300",
      "deployments": "300",
      "statefulsets": "300",
      "pods": "300",
      "nodes": "300",
      "services": "300",
      "replicasets": "900",
      "ingresses": "300",
      "jobs": "300",
      "pv": "300",
      "persistentvolumeclaim": "300",
      "componentstatuses": "300",
      "horizontalpodautoscalers": "300",
      "endpoints": "3600",
      "namespaces": "300",
      "eventcollector": "60",
      "npcdatacollector": "300",
      "npcdatacollector_discovery": "900",
      "resourcedependency": "300",
      "workloadsdatacollector": "300",
      "workloadsdatacollector_discovery": "900",
      "clustermetricsaggregator": "300",
      "sidecarnpccollector": "300",
      "sidecarnpccollector_discovery": "900",
      "dcinit": "900",
      "clusteragent": "1",
      "ksm": "1",
      "guidancemetrics": "20600",
      "termination": "900",
      "kubelet": "300",
      "metadata": "20600",
      "prometheus_integration": "1",
      "plugin_integration": "1",
      "database_integration": "1",
      "ksmprocessor": "1",
      "kubeletdatapersistence": "1",
      "servicerelationdataprocessor": "1",
      "yamlfetcher": "60"
    }
  1MIN: |
    {
      "Pods": "90",
      "Nodes": "90",
      "Namespaces": "90",
      "HorizontalPodAutoscalers": "-1",
      "DaemonSets": "90",
      "Deployments": "60",
      "Endpoints": "-1",
      "ReplicaSets": "-1",
      "StatefulSets": "90",
      "Services": "-1",
      "PV": "-1",
      "PersistentVolumeClaims": "-1",
      "Jobs": "-1",
      "Ingresses": "-1"
    }
{{ end }}