# Default values for site24x7-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# names used for site24x7 resources
nameOverride: "site24x7"
fullnameOverride: "site24x7"

# site24x7 device key
deviceKey: "apiKey"

# Cluster distributions
openShift: false
gkeAutopilot: false

# associate Existing priorityClass to the site24x7 pods
associateExistingPriorityClass: ""

# configMap used for storing the site24x7 settings & configurations
createConfigMap: true

# proxy settings for site24x7-agent & site24x7-cluster-agent
http_proxy: ""
https_proxy: ""

site24x7Agent:
  create: true

  # daemonset and pod annotations
  annotations: {}

  # updateStrategy for daemonset
  updateStrategy: {}

  # nodeSelector for daemonset pods
  nodeSelector: {}

  # list of tolerations to add to the daemonset pods
  tolerations: []

  # securityContext to be applied to the daemonset containers
  securityContext: {}

  # if not securityContext is provided, the appropriate context to be added to the daemonset containers based runAsNonRoot: true/false
  applyNonRootSecurityContext: false

  # applying toleration which tolerates any taints
  applyDefaultToleration: true

  # daemonset container details
  image:
    repository: site24x7
    name: docker-agent
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: release2000
    imagePullSecrets: []

  # site24x7-agent container resources
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

  # extraEnv to be added to the site24x7-agent container
  extraEnv: []

  # apply the site24x7-agent priorityClass to the daemonset pods
  applyPriorityClass: true

  # site24x7-agent priorityClass value
  priorityClassValue: 12000000
  
site24x7KubeStateMetrics:
  # kube-state-metrics enable/disable
  create: true

  # deployment and pod annotations
  annotations: {}

  # updateStrategy for deployment
  updateStrategy: {}

  # nodeSelector for deployment pods
  nodeSelector: {}

  # list of tolerations to add to the deployment pods
  tolerations: []

  # securityContext to be applied to the deployment contaiers
  securityContext: {}

  # replicas count of site24x7-kube-state-metrics deployment
  replicas: 1

  # applying toleration which tolerates any taints
  applyDefaultToleration: false

  # deployment container details
  image:
    repository: registry.k8s.io
    name: kube-state-metrics/kube-state-metrics
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v2.9.2
    imagePullSecrets: []
  
  # site24x7-agent container resources
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  # apply the site24x7-kube-state-metrics priorityClass to the daemonset pods
  applyPriorityClass: true

  # site24x7-kube-state-metrics priorityClass value
  priorityClassValue: 12000000
  
site24x7ClusterAgent:
  # kube-state-metrics enable/disable
  create: true

  # replicas
  replicas: 1

  # deployment and pod annotations
  annotations: {}

  # updateStrategy for deployment
  updateStrategy: {}

  # nodeSelector for deployment pods
  nodeSelector: {}
  
  # list of tolerations to add to the deployment pods
  tolerations: []

  # securityContext to be applied to the deployment contaiers
  securityContext: {}

  # applying toleration which tolerates any taints
  applyDefaultToleration: false

  # deployment container details
  image:
    repository: site24x7
    name: docker-agent
    # Overrides the image tag whose default is the chart appVersion.
    tag: cluster_agent_nonroot
    pullPolicy: IfNotPresent
    imagePullSecrets: []
  
  # site24x7-agent container resources
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 800Mi
  
  # extraEnv to be added to the site24x7-agent container
  extraEnv: []

  # apply the site24x7-cluster-agent priorityClass to the daemonset pods
  applyPriorityClass: true

  # site24x7-cluster-agent priorityClass value
  priorityClassValue: 12000000

serviceAccount:
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: site24x7