{{- if .Values.site24x7ClusterAgent.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "site24x7ClusterAgent.name" . }}
  labels:
    {{- include "site24x7ClusterAgent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.site24x7ClusterAgent.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "site24x7.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "site24x7ClusterAgent.labels" . | nindent 8 }}
        app: {{ include "site24x7ClusterAgent.name" . }}
      name: {{ include "site24x7ClusterAgent.name" . }}
    spec:
      serviceAccountName: {{ include "site24x7.fullname" . }}
      containers:
      - image: site24x7/docker-agent:cluster_agent_nonroot
        imagePullPolicy: Always
        name: site24x7-cluster-agent
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                  fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CLUSTER_AGENT
            value: "true"
          {{- if and .Values.http_proxy .Values.https_proxy }}
          - name: http_proxy
            value: {{ .Values.http_proxy }}
          - name: https_proxy
            value: {{ .Values.https_proxy }}
          {{- end }}
        ports:
          - containerPort: 5000
            name: http-metrics
            protocol: TCP
        securityContext:
          {{- include "site24x7.nonRootScc" . | indent 10 }}
        volumeMounts:
          - name: site24x7-cluster-agent
            mountPath: /home/site24x7/monagent
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "450Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /ca/health_check
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 5
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /ca/health_check
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 5
          timeoutSeconds: 10
      volumes:
      - emptyDir: {}
        name: site24x7-cluster-agent
{{ end }}