{{- if .Values.site24x7ClusterAgent.create }}
apiVersion: v1
kind: Service
metadata:
  name: site24x7-cluster-agent
  namespace: default
  labels:
    app.kubernetes.io/name: site24x7-cluster-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/owner: site24x7
    app.kubernetes.io/version: 1.0.0
spec:
  ports:
  - name: http-metrics
    port: 5000
    protocol: TCP
  selector:
    app.kubernetes.io/name: site24x7-cluster-agent
{{ end }}